export default {
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
    CHANGE_LANGUAGE_STORE: 'CHANGE_LANGUAGE_STORE',
    GET_NEWS: 'GET_NEWS',
    GET_NEWS_STORE: 'GET_NEWS_STORE',
    READ_NEWS: 'READ_NEWS',
    READ_NEWS_STORE: 'READ_NEWS_STORE',
    CLOSE_NEWS: 'CLOSE_NEWS',
    CLOSE_NEWS_STORE: 'CLOSE_NEWS_STORE'
}


